callbacks:
  early_stop_patience: 10
  scheduler_patience: 4
datamodule:
  batch_size: 1024
  overlap: 29
  seq_len: 30
model_dim:
  hidden_dim: 10
  input_dim: 142
  n_layers: 1
  output_dim: 2
model_hparams:
  dropout: 0.2
  gauss_noise: true
  learn_rate: 0.0006
  weight_decay: 0.001
real-time:
  saved_scalars: /home/bbhaduri/Projects/RNN_scalars_07-15-22_16:06:53.pkl
  saved_weights: /home/bbhaduri/Projects/RNN_weights_07-15-22_16:06:53.pt
training:
  bin_size: 0.005
  data_dir: 
  log_name: RNN_model_
  log_pth: 
  max_epochs: 1000
  n_steps: 1
  save_pth: 
  train_pct: 0.7
  val_pct: 0.2
