name: rt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.0.2
  - python=3.8.2
  - readline=8.0
  - setuptools=46.4.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - argparse==1.4.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bidict==0.22.0
    - bleach==3.1.5
    - click==7.1.2
    - coloredlogs==15.0.1
    - cycler==0.10.0
    - cython==0.29.18
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dnspython==2.2.1
    - entrypoints==0.3
    - eventlet==0.25.1
    - flask==1.1.2
    - flask-cors==3.0.8
    - flask-socketio==4.2.1
    - greenlet==1.1.2
    - h5py==3.3.0
    - hdmf==3.3.1
    - humanfriendly==10.0
    - ipykernel==5.2.1
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jedi==0.17.0
    - jinja2==2.11.2
    - joblib==1.1.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - monotonic==1.6
    - mpmath==1.1.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - nose==1.3.7
    - notebook==6.0.3
    - numpy==1.18.4
    - packaging==20.3
    - pandas==1.3.2
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickle5==0.0.11
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - psutil==5.9.1
    - ptyprocess==0.6.0
    - pygame==2.0.0
    - pyglet==1.5.11
    - pygments==2.6.1
    - pynwb==2.0.0
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - python-engineio==4.3.2
    - python-socketio==5.6.0
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - redis==3.5.3
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.1.1
    - scipy==1.4.1
    - send2trash==1.5.0
    - six==1.14.0
    - sklearn==0.0
    - sympy==1.5.1
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==3.1.0
    - tornado==6.0.4
    - traitlets==4.3.3
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - yapf==0.32.0
    - -e ./lib/python

